### ISSUE TITLE
Ignore storageclasses that are known to be unsuitable for running VMs

### ISSUE THREAD

**Issue by aglitke** [kiagnose/kubevirt-storage-checkup#12]
When testing this on a cluster with ODF I get the following error:

status.failureReason: 'There are StorageProfiles with empty ClaimPropertySets (unknown
    provisioners): ocs-storagecluster-ceph-rgw, openshift-storage.noobaa.io.'

CDI [recognizes](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/storagecapabilities/storagecapabilities.go#L133) these two provisioners as unsupported for running VMs.  We should probably have a check that lists the storage classes which are unsupported and exclude them from the empty claimPropertySets check.

**Comment by arnongilboa** [comment]
Fixed by #15
